name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install deps
        run: npm ci

      - name: Detect CNAME and set baseURL
        run: |
          if [ -f public/CNAME ]; then
            echo "Detected CNAME, set baseURL=/"
            echo "NUXT_APP_BASE_URL=/" >> $GITHUB_ENV
          elif [[ "${{ github.event.repository.name }}" != *".github.io" ]]; then
            echo "Project pages repo without CNAME, set baseURL=/${{ github.event.repository.name }}/"
            echo "NUXT_APP_BASE_URL=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
          else
            echo "User/Org pages repo, baseURL=/"
            echo "NUXT_APP_BASE_URL=/" >> $GITHUB_ENV
          fi

      - name: Generate static site
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


